overall_time_limit: 86400 # 24 hours in second
batch_settings:
  batch_repetitions: 2
  # Set to true to automatically start the next batch after the current one finishes.
  # If false, the user must press "Start" for each batch.
  # The first batch always requires a manual "Start" press.
  auto_start_next_batch: True # Default to false (manual start)
  
  # Delay in seconds before automatically starting the next batch.
  # Only used if auto_start_next_batch is true.
  auto_start_delay_seconds: 2

equipment:
- name: keysight_970A_daq
  class: daq_keysight #class file
  type: DAQ
  connection:
    mode: VISA
    address: USB0::0x2A8D::0x5101::MY58032659::0::INSTR
  schedule:
    # sample_interval: 0.4
    schedule_csv: schedule_daq.csv
  settings:
    channels:
        - channel: "101:105"
          measurement: "TEMP:TC"
          sensor_type: "T"
          remark: "TC T-type temperature"
        - channel: "106:108"
          measurement: "VOLT:DC"
          sensor_type: "10"
          remark: "Sensors"
        - channel: "201:203, 208:210"
          measurement: "FRES" #RES for 2-wire
          sensor_type: "100" #AUTO
          remark: "4-wire resistance"
- name: korad_ka3005_pump
  class: psu_ka3005
  type: PowerSupply
  connection:
    mode: VISA
    address: ASRL3::INSTR
  schedule:
    schedule_csv: schedule_pump.csv
  settings:
    max_current: 5
    max_voltage: 30

- name: keysight_e36155_heater
  class: psu_e36155
  type: PowerSupply
  connection:
    mode: VISA
    address: USB0::0x2A8D::0x5902::MY63000128::0::INSTR
  schedule:
    schedule_csv: schedule_heater.csv
  settings:
    max_current: 5
    max_voltage: 30

- name: dd450_bath
  class: bath_dd450
  type: Bath
  connection:
    mode: VISA
    address: ASRL6::INSTR
  schedule:
    schedule_csv: schedule_bath.csv
  settings:
    max_current: 5
    max_voltage: 30
# - name: leadfluid_ct3000f
#   class: pump_ct3000f
#   type: pump
#   connection:
#     mode: MODBUS
#     address: COM10
#     framer: rtu
#     baudrate: 9600
#     parity: E
#     stopbits: 1
#     bytesize: 8
#     unit: 1
#   schedule:
#     schedule_csv: schedule_pump.csv
#   settings:
#     max_current: 5
#     max_voltage: 30

idle_monitoring:
  enabled: true
  interval_seconds: 10
  equipment_name: "keysight_970A_daq" # Name of the DAQ to use for idle reads
  # Channel IDs (as defined in the DAQ's scan list, e.g., "101", "106")
  # to be displayed during idle monitoring. These must be part of the DAQ's
  # main scan list configured during its initialization.
  display_channel_ids: ["101", "108"] # Example: display data for channels 101, 106

safety_rules:
  enabled: true
  check_interval_seconds: 2 # How often to check safety conditions
  initial_ramp_up_delay_seconds: 15
  rules:
    - name: "Ch101_OverTemp"
      enabled: true
      channel_id: "Channel_101" # This MUST match the channel ID string used in DataManager (e.g., "Channel_101")
      condition: "greater_than" # "greater_than", "less_than", "outside_range" (threshold would be [min, max])
      threshold: 70 # Single value for greater_than/less_than, list for outside_range [low, high]
      action: "shutdown" # "shutdown" or "warning_only"
      message: "SAFETY ALERT: Channel 101 temperature critical (> 60 C)!"
      # persistence_readings: 3 # Optional: condition must be met for X consecutive valid readings

    - name: "Ch108_VoltageLow"
      enabled: true
      channel_id: "Channel_108"
      condition: "less_than"
      threshold: 0.5
      action: "shutdown"
      message: "SAFETY WARNING: Channel 108 voltage is low (< 0.5 V)."