overall_time_limit: 5 #28800 # 8 hours in second
equipment:
- name: keysight
  class: KeysightDAQ #class file
  type: DAQ
  connection:
    mode: VISA
    address: GPIB0::23::INSTR
  schedule:
    sample_rate: 1
    # schedule_csv: data.csv
  settings:
    channels:
        - channel: "101:105"
          measurement: "TEMP:TC"
          sensor_type: "T"
          remark: "TC T-type temperature"
        - channel: "106:108"
          measurement: "TEMP:TC"
          sensor_type: "T"
          remark: "TC T-type temperature"
        - channel: "109:115"
          measurement: "RES"
          sensor_type: "AUTO"
          remark: "resistance"
- name: simu_daq
  class: simu_daq
  type: DAQ
  connection:
    mode: VISA
    address: GPIB0::23::INSTR
  schedule:
    sample_rate: 2
    # schedule_csv: data1.csv
  settings:
    channels:
        - channel: "201"
          measurement: "TEMP:TC"
          sensor_type: "K"
          remark: "TC K-type temperature"
        - channel: "202:203"
          measurement: "TEMP:TC"
          sensor_type: "T"
          remark: "TC T-type temperature"
        - channel: "204:205"
          measurement: "RES"
          sensor_type: "AUTO"
          remark: "resistance"
- name: ke
  class: simu_psu
  type: PowerSupply
  connection:
    mode: Modbus
    address: 192.168.1.100
    port: 502
  schedule:
    schedule_csv: data.csv
  settings:
    max_current: 5
    max_voltage: 30
# - name: ka3005
#   class: Ka3005PSU
#   type: PowerSupply
#   connection:
#     mode: VISA
#     address: ASRL3::INSTR
#   schedule:
#     schedule_csv: data.csv
#   settings:
