overall_time_limit: 126400 # 24 hours in second
equipment:
- name: keysight_970A_daq
  class: daq_keysight #class file
  type: DAQ
  connection:
    mode: VISA
    address: USB0::0x2A8D::0x5101::MY58032659::0::INSTR
  schedule:
    # sample_interval: 0.4
    schedule_csv: schedule_daq_cal.csv
  settings:
    channels:
        - channel: "101:105"
          measurement: "TEMP:TC"
          sensor_type: "T"
          remark: "TC T-type temperature"
        - channel: "106:108"
          measurement: "VOLT:DC"
          sensor_type: "10"
          remark: "Sensors"
        - channel: "201:203, 208:210"
          measurement: "FRES" #RES for 2-wire
          sensor_type: "100" #AUTO
          remark: "4-wire resistance"
- name: korad_ka3005_pump
  class: psu_ka3005
  type: PowerSupply
  connection:
    mode: VISA
    address: ASRL3::INSTR
  schedule:
    schedule_csv: schedule_pump_cal.csv
  settings:
    max_current: 5
    max_voltage: 30
# - name: keysight_e36155_heater
#   class: psu_e36155
#   type: PowerSupply
#   connection:
#     mode: VISA
#     address: USB0::0x2A8D::0x5902::MY63000128::0::INSTR
#   schedule:
#     schedule_csv: schedule_heater.csv
#   settings:
#     max_current: 5
#     max_voltage: 30
- name: dd450_bath
  class: bath_dd450
  type: Bath
  connection:
    mode: VISA
    address: ASRL6::INSTR
  schedule:
    schedule_csv: schedule_bath_cal.csv
  settings:
    max_current: 5
    max_voltage: 30
    - name: leadfluid_ct3000f
  # class: pump_ct3000f
  # type: pump
  # connection:
  #   mode: MODBUS
  #   address: COM10
  #   framer: rtu
  #   baudrate: 9600
  #   parity: E
  #   stopbits: 1
  #   bytesize: 8
  #   unit: 1
  # schedule:
  #   schedule_csv: schedule_pump_cal.csv
  # settings:
  #   max_current: 5
  #   max_voltage: 30